---
_yaml:
  _version: 0.3.1
  app: quiltcore
  app_version: 0.5.0
  doc: quiltspec
  doc_version: 0.2.0
config:
  udi: quilt+s3://udp-spec#package=spec/catalog:1689200152
  registry: s3://udp-spec
  namespace: spec/catalog
  tag: 1689200152
  hash: 124225d173a046212950e5bde7a84f365abef2e969e6f7b2a808c5f7322aa6e9
  update: timestamp.txt
files:
  READ ME.md: This is the README for QuiltSpec.
  timestamp.txt: 2023-07-13T23:09:50+0000
metadata:
  _package:
    Author: Ernest
    Count: 1
    Date: 2023-07-12
  timestamp.txt:
    format: iso8601
workflow:
  version: "1"
  successors:
    s3://udp-spec:
      title: QuiltSpec for Universal Data Products
  is_workflow_required: false
  default_workflow: universal
  workflows:
    universal:
      name: Universal
      metadata_schema: universal
  schemas:
    universal:
      url: s3://udp-spec/.quilt/workflows/universal.json
